version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: gfw/docker-airflow
        build: .
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
             - /Users/paul/github/pipe-model/pipe-orbcomm-airflow:/usr/local/airflow/dags/pipe-orbcomm-airflow
             - ./initialize:/usr/local/airflow/initialize
        ports:
            - "8080:8080"
        command: webserver
