version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: gfw/docker-airflow
        build: .
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW_HOME=/usr/local/airflow
            # Note that this means that this must be run from airflow directory.
            - HOST_DAGS=${PWD}/dags 
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver

